### ISSUE TITLE
We need a unified version, and using master code is an unstable thing.

### ISSUE THREAD

**Issue by 99Kies** [Diora-Network/Diora#1]
The latest parallel chain should use version 0.9.23.

**Comment by DappGuy** [comment]
we are currently using nimbus which is on 0.9.10 https://github.com/PureStake/nimbus

i was worried about version conflicts if we upgraded onto 0.9.23 what did you think?

**Comment by DappGuy** [comment]
i have merged https://github.com/Diora-Network/Diora/commit/c9ffd9ab158988fd85516c2eb742b431b4dc0d03

**Comment by 99Kies** [comment]
> we are currently using nimbus which is on 0.9.10 https://github.com/PureStake/nimbus
> 
> i was worried about version conflicts if we upgraded onto 0.9.23 what did you think?

Now the latest version is 23, I think this is not a big problem.
